apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-update-1-sept13-app
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/pipeline-update-1-sept13/overlays/development
    repoURL: https://github.com/jdubrick-ai/pipeline-update-1-sept13-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
