apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pipeline-update-1-sept13 
  janus-idp.io/tekton: pipeline-update-1-sept13
  backstage.io/kubernetes-id: pipeline-update-1-sept13
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pipeline-update-1-sept13
resources: 
- application-dev.yaml