apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-pipeline-update-1-sept13-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-pipeline-update-1-sept13-gitops
    spec:  
      serviceAccountName: pipeline-update-1-sept13-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=pipeline-update-1-sept13-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/pipeline-update-1-sept13-notebook -- git clone https://github.com/jdubrick-ai/pipeline-update-1-sept13
      restartPolicy: Never